meta_product_name: "GroupnGo"
meta_title: "GroupnGo - Come together, pay less"
meta_description: "Pay less for your favorite activites by joining a group and benefiting from discounted group’s prices."
meta_image: "image-groupngo.png" # should exist in `app/assets/images/`
 # required for Twitter Cards
